### PR TITLE
Dev 2.8.0

### PR DESCRIPTION
**Pull request by corbin-chris**
**21st November 2022: Pre-review information**
**Summary**
This app runs FusionInspector, a tool which takes in candidate fusions from STAR-Fusion and rescue lists, and re-scores the evidence for the fusions, partly through re-mapping to fusion contigs. Optionally, the user can use the Trinity option, which carries out an additional step for de novo reconstruction. 
This app is specifically set up to process the 'Chimeric.out.junction' files produced by the earlier STAR-Aligner alignment step. It produces files of candidate fusion regions and supporting evidence.
See the README for input and output options.

**Demonstration - without Trinity option**
The user may run the app without Trinity, which outputs fewer files.
I made a project to run the example in: 
project-GJqqBK04JkPBQyJ6PjybFypx
The app was run in the following job: 
job-GJxb7784y9fzZQPGKVZBpG3v
Using this applet:
applet-GJxZY5Q4y9fZgXxb3j46gPkx

I added a requirement that FASTQ files and predictions have matching sample names. I needed to move/rename a predictions file to make this work:
```
dx select project-GJqgYF04y9fb4Kv13FK1BGyX
dx mv SeraSeqControl_S8.star-fusion.fusion_predictions.tsv SeraSeqControl.star-fusion.fusion_predictions.tsv
file-GJVBKfQ4YF8XYXvGGJ6BzB0k
```

I then ran eggd_fusioninspector without Trinity as follows:
```
dx run project-GJqgYF04y9fb4Kv13FK1BGyX:/eggd_fusioninspector \
-ifi_docker=file-GGzFp2Q43Gg5Y56p8yfGjPYb \
-ir1_fastqs=file-GBBG8Vj425gx12GQPKpQzzQG \
-ir1_fastqs=file-GBBG970425gzPyqPPXk9YJYk \
-ir2_fastqs=file-GBBG8X8425gggYxfPX650z6Q \
-ir2_fastqs=file-GBBG97Q425gQpky77F0GPbFk \
-iknown_fusions=file-Fvxx0z04pgK02fK17f52x6g2 \
-isr_predictions=file-GJVBKfQ4YF8XYXvGGJ6BzB0k \
-igenome_lib=file-GJfX12j41p4GY5K3PY65VFjj \
-iinclude_trinity=false
```

Output files:
SeraSeqControl.FusionInspector.fusions.tsv: file-GJxf7Pj47j86bxX4GPfV9YKV
SeraSeqControl.FusionInspector.fusions.abridged.tsv: file-GJxf7Pj47j8KjPy19fjGKJjz
SeraSeqControl.FusionInspector.fusions.abridged.tsv.coding_effect: file-GJxf7Pj47j8K1PZYJjJ1BQFp
SeraSeqControl.fusion_inspector_web.html: file-GJxf7Pj47j80f19xJj0GQ1b5

**Demonstration - with Trinity option**
Running with Trinity generates more evidence files.
Examples are in this project:
project-GJqgXXj4ZY2zv2q43B99z7Yp
The app was run in the following job: 
job-GJxb6xj4ZY2qyxFg4K6Zqg4v
Using this applet:
applet-GJxZXp84ZY2Y5zj47Yb6K5xF

I added a requirement that FASTQ files and predictions have matching sample names. I needed to move/rename a predictions file to make this work:
```
dx select project-GJqgXXj4ZY2zv2q43B99z7Yp
dx mv SeraSeqControl_S8.star-fusion.fusion_predictions.tsv SeraSeqControl.star-fusion.fusion_predictions.tsv
```
I then ran eggd_fusioninspector with Trinity:
```
dx run project-GJqgXXj4ZY2zv2q43B99z7Yp:/eggd_fusioninspector \
-ifi_docker=file-GGzFp2Q43Gg5Y56p8yfGjPYb \
-ir1_fastqs=file-GBBG8Vj425gx12GQPKpQzzQG \
-ir1_fastqs=file-GBBG970425gzPyqPPXk9YJYk \
-ir2_fastqs=file-GBBG8X8425gggYxfPX650z6Q \
-ir2_fastqs=file-GBBG97Q425gQpky77F0GPbFk \
-iknown_fusions=file-Fvxx0z04pgK02fK17f52x6g2 \
-isr_predictions=file-GJVBKfQ4YF8XYXvGGJ6BzB0k \
-igenome_lib=file-GJfX12j41p4GY5K3PY65VFjj \
-iinclude_trinity=true
```

Output files:
SeraSeqControl.FusionInspector.fusions.tsv: file-GJxf99043jkG6PzJ9z9J7kZK
SeraSeqControl.FusionInspector.fusions.abridged.tsv: file-GJxf99043jk76q97K3gvqxPp
SeraSeqControl.FusionInspector.fusions.abridged.tsv.coding_effect: file-GJxf99043jk7JbYbGK9ZPJ2F
SeraSeqControl.fusion_inspector_web.html: file-GJxf99043jk0K5ff9zXVg6j3
SeraSeqControl.gmap_trinity_GG.fusions.fasta: file-GJxf99043jkBj4xpJq4gpKpZ
SeraSeqControl.gmap_trinity_GG.fusions.gff3: file-GJxf99043jkGVpJv8xyjzzvz
SeraSeqControl.gmap_trinity_GG.fusions.gff3: file-GJxf99043jkGVpJv8xyjzzvz

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_fusioninspector/1)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_fusioninspector/1)* status: all files reviewed, 2 unresolved discussions (waiting on @corbin-chris and @kjwinfield)

___
*[`dxapp.json` line 4 at r3](https://reviewable.io/reviews/eastgenomics/eggd_fusioninspector/1#-NHV-nNuA0ykw70eNuYJ:-NHV-nNuA0ykw70eNuYK:b-h56yek) ([raw file](https://github.com/eastgenomics/eggd_fusioninspector/blob/7c07a7625d8d72732603c4e9862f1537a4db4430/dxapp.json#L4)):*
> ```JSON
>   "name": "eggd_fusioninspector",
>   "title": "eggd_fusioninspector",
>   "summary": "App which runs FusionInspector v2.8.0 in the official Docker. It identifies fusions using known 'rescue list' fusion pairs, plus predictions from STAR-Fusion",
> ```

Does this run only v2.8.0, or whatever docker image you pass to it?



_Code quote:_
```JSON
FusionInspector v2.8.0
```
___
*[`dxapp.json` line 24 at r3](https://reviewable.io/reviews/eastgenomics/eggd_fusioninspector/1#-NHYz8Q13pGVeJqDqDUH:-NHYz8Q13pGVeJqDqDUI:b-mx4tbg) ([raw file](https://github.com/eastgenomics/eggd_fusioninspector/blob/7c07a7625d8d72732603c4e9862f1537a4db4430/dxapp.json#L24)):*
> ```JSON
>       "optional": false,
>       "patterns": [
>         "*.fastq.gz"
> ```

Should we also accept `*.fq.gz` here?



_Code quote:_
```JSON
"*.fastq.gz"
```

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_fusioninspector/1)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @kjwinfield and @mattgarner)

*[a discussion](https://reviewable.io/reviews/eastgenomics/eggd_fusioninspector/1#-NI2zrpH6jPd3dZOVYiJ:-NI2zrpH6jPd3dZOVYiK:bbvpzk8) (no related file):*
29th November 2022: Further changes made

* Fusion read evidence files, generated by flag '--extract_fusion_reads_file', are now written out as DNA Nexus outputs.
* Example fusion evidence files produced by the tool are in project-GJqgYF04y9fb4Kv13FK1BGyX:
file-GK327Y04KVxq19ZF4pyz9xq5
file-GK327Y04KVxQxF0b9z54Y7ZB

___
___
*[`dxapp.json` line 4 at r3](https://reviewable.io/reviews/eastgenomics/eggd_fusioninspector/1#-NHV-nNuA0ykw70eNuYJ:-NHe6YSS2piUxD7LrdWk:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_fusioninspector/blob/7c07a7625d8d72732603c4e9862f1537a4db4430/dxapp.json#L4)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Does this run only v2.8.0, or whatever docker image you pass to it?
</blockquote></details>

Done.
___
*[`dxapp.json` line 24 at r3](https://reviewable.io/reviews/eastgenomics/eggd_fusioninspector/1#-NHYz8Q13pGVeJqDqDUH:-NHe6zUzDDQAoQ-qpgNx:b-9eh21k) ([raw file](https://github.com/eastgenomics/eggd_fusioninspector/blob/7c07a7625d8d72732603c4e9862f1537a4db4430/dxapp.json#L24)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Should we also accept `*.fq.gz` here?
</blockquote></details>

No idea, I've not worked anywhere using .fq instead of .fastq but I don't know how it is here. Will add it to patterns and change file-finding in code.

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r5, 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_fusioninspector/1)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @corbin-chris and @kjwinfield)

___
*[`dxapp.json` line 24 at r3](https://reviewable.io/reviews/eastgenomics/eggd_fusioninspector/1#-NHYz8Q13pGVeJqDqDUH:-NIC-nO58rdLd_RElsk5:bp1sz70) ([raw file](https://github.com/eastgenomics/eggd_fusioninspector/blob/7c07a7625d8d72732603c4e9862f1537a4db4430/dxapp.json#L24)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

No idea, I've not worked anywhere using .fq instead of .fastq but I don't know how it is here. Will add it to patterns and change file-finding in code.
</blockquote></details>

Thanks, we do have some old fastqs names as fq.gz, though I'm sure they will never be used with this. 

I was really only asking since I noticed that you also handle fq.gz in `_trim_fastq_endings()` within the code. 
___
*[`dxapp.json` line 127 at r6](https://reviewable.io/reviews/eastgenomics/eggd_fusioninspector/1#-NIC1PSE9poghG_m9Z18:-NIC1PSE9poghG_m9Z19:bhhdwtb) ([raw file](https://github.com/eastgenomics/eggd_fusioninspector/blob/cd3a966cb70faf9745e36fbad607b46436d303c1/dxapp.json#L127)):*
> ```JSON
>       "optional": false,
>       "help": "A file of R2 reads which mapped to fusions"
>     },
> ```

Could this include a description of the file type?

(Also please see my later comments on these files before doing this!)



_Code quote:_
```JSON
    {
      "name": "fi_fusion_r1",
      "label": "fi_fusion_reads_1",
      "class": "file",
      "optional": false,
      "help": "A file of R1 reads which mapped to fusions"
    },
    {
      "name": "fi_fusion_r2",
      "label": "fi_fusion_reads_2",
      "class": "file",
      "optional": false,
      "help": "A file of R2 reads which mapped to fusions"
    },
```
___
*[`README.md` line 46 at r6](https://reviewable.io/reviews/eastgenomics/eggd_fusioninspector/1#-NIC1p1FBRj-GWSljDLR:-NIC1p1FBRj-GWSljDLS:b-ex7ns3) ([raw file](https://github.com/eastgenomics/eggd_fusioninspector/blob/cd3a966cb70faf9745e36fbad607b46436d303c1/README.md#L46)):*
> ```Markdown
>     * fi_coding: the abridged FusionInspector output containing additional information about potential coding effect, a tsv file 
>     * fi_html: a HTML of fusion evidence which can be viewed in-browser.
>     * fi_fusion_r1: read 1s which FusionInspector mapped to the fusions.
> ```

File format for these?



_Code quote:_
```Markdown
fi_fusion_r1: read 1s which FusionInspector mapped to the fusions.
```
___
*[`src/code.sh` line 183 at r6](https://reviewable.io/reviews/eastgenomics/eggd_fusioninspector/1#-NIC22xS3j5d4i_O67vi:-NIC22xS3j5d4i_O67vj:b-izxy1w) ([raw file](https://github.com/eastgenomics/eggd_fusioninspector/blob/cd3a966cb70faf9745e36fbad607b46436d303c1/src/code.sh#L183)):*
> ```Shell
> 
> find /home/dnanexus/temp_out -type f -name "${prefix}.fusion_evidence_reads_*2*" -printf "%f\n" | \
> xargs -I{} mv /home/dnanexus/temp_out/{} /home/dnanexus/out/fi_fusion_r2/"${prefix}".{}
> ```

These are fastqs named `fq`, which is inconsistent with the input fastqs being named `fastq`

Could we name them `fastq` instead, and consider whether they should also be gzipped (i.e. fastq.gz) before being passed to output?



_Code quote:_
```Shell
find /home/dnanexus/temp_out -type f -name "${prefix}.fusion_evidence_reads_*1*" -printf "%f\n" | \
xargs -I{} mv /home/dnanexus/temp_out/{} /home/dnanexus/out/fi_fusion_r1/"${prefix}".{}

find /home/dnanexus/temp_out -type f -name "${prefix}.fusion_evidence_reads_*2*" -printf "%f\n" | \
xargs -I{} mv /home/dnanexus/temp_out/{} /home/dnanexus/out/fi_fusion_r2/"${prefix}".{}
```

**Review by corbin-chris — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_fusioninspector/1)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @kjwinfield and @mattgarner)

___
*[`dxapp.json` line 127 at r6](https://reviewable.io/reviews/eastgenomics/eggd_fusioninspector/1#-NIC1PSE9poghG_m9Z18:-NIHB1j29RXSdH7sz3EC:b-75u96a) ([raw file](https://github.com/eastgenomics/eggd_fusioninspector/blob/cd3a966cb70faf9745e36fbad607b46436d303c1/dxapp.json#L127)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could this include a description of the file type?

(Also please see my later comments on these files before doing this!)
</blockquote></details>

Put that they are gzipped FASTQ files.
___
*[`README.md` line 46 at r6](https://reviewable.io/reviews/eastgenomics/eggd_fusioninspector/1#-NIC1p1FBRj-GWSljDLR:-NIHBS9qDMc97N0wYvbx:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_fusioninspector/blob/cd3a966cb70faf9745e36fbad607b46436d303c1/README.md#L46)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

File format for these?
</blockquote></details>

Done.
___
*[`src/code.sh` line 183 at r6](https://reviewable.io/reviews/eastgenomics/eggd_fusioninspector/1#-NIC22xS3j5d4i_O67vi:-NIHBWZq5yEI7mkyJAak:b-xoh7il) ([raw file](https://github.com/eastgenomics/eggd_fusioninspector/blob/cd3a966cb70faf9745e36fbad607b46436d303c1/src/code.sh#L183)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

These are fastqs named `fq`, which is inconsistent with the input fastqs being named `fastq`

Could we name them `fastq` instead, and consider whether they should also be gzipped (i.e. fastq.gz) before being passed to output?
</blockquote></details>

They now rename to .fastq and are gzipped before moving to the final folder.
For examples see:
file-GK4yKG04Xv6XzbB85xK9yp1f
file-GK4yKG04Xv6xBZxV61pQXbPp
Generated by: job-GK4xb484y9fX58Z175B2F15v
In project: project-GJqgYF04y9fb4Kv13FK1BGyX

**Review by mattgarner — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_fusioninspector/1)* status: all files reviewed, 1 unresolved discussion (waiting on @kjwinfield)

**Pull request merged**
